activity_paths = [
  "example/activities.txt",
  "example/extra_activities.txt",
]

[quadrants]
# urgent and important
1 = ["@work"]

# non-urgent and important
2 = [
  "@sleep",
  "@routine",
  "@health",
]

# urgent and unimportant
3 = [
  "@news",
  "@calls",
  "@meeting",
]

# non-urgent and unimportant
4 =[
  "@proc",
  "@twitch",
  "@misc",
]

# maintenance, necessary
5 = [
  "@eat",
  "@shower",
  "@groceries",
  "@food",
]
